services:
    sonata.admin.operador:
          class: Timsa\ControlFletesBundle\Admin\OperadorAdmin
          tags:
                - {name: sonata.admin, manager_type: orm, group: Principales, label: "Operadores"}
          arguments:
                - ~
                - Timsa\ControlFletesBundle\Entity\Operador
                - 'TimsaControlFletesBundle:Admin'

    sonata.admin.economico:
        class: Timsa\ControlFletesBundle\Admin\EconomicoAdmin
        tags:
            - {name: sonata.admin, manager_type: orm, group: Principales, label: "Economico"}
        arguments:
              - ~
              - Timsa\ControlFletesBundle\Entity\Economico
              - 'TimsaControlFletesBundle:Admin'

    sonata.admin.socio:
        class: Timsa\ControlFletesBundle\Admin\SocioAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: Principales, label: "Socio" }
        arguments:
            - ~
            - Timsa\ControlFletesBundle\Entity\Socio
            - 'TimsaControlFletesBundle:Admin'
        calls:
            - [ setTranslationDomain, [YourNSAdminBundle]]


    sonata.admin.relacion:
        class: Timsa\ControlFletesBundle\Admin\RelacionAdmin
        tags:
            - {name: sonata.admin, manager_type: orm, group: Principales, label: "Relacion"}
        arguments:
              - ~
              - Timsa\ControlFletesBundle\Entity\Relacion
              - 'TimsaControlFletesBundle:Admin'

    sonata.admin.cliente:
        class: Timsa\ControlFletesBundle\Admin\ClienteAdmin
        tags:
            - {name: sonata.admin, manager_type: orm, group: Operacionales, label: "Clientes"}
        arguments:
              - ~
              - Timsa\ControlFletesBundle\Entity\Cliente
              - 'TimsaControlFletesBundle:Admin'

    sonata.admin.sucursal:
        class: Timsa\ControlFletesBundle\Admin\SucursalAdmin
        tags:
            - {name: sonata.admin, manager_type: orm, group: Operacionales, label: "Destinos"}
        arguments:
              - ~
              - Timsa\ControlFletesBundle\Entity\Sucursal
              - 'TimsaControlFletesBundle:Admin'

    sonata.admin.agencia:
        class: Timsa\ControlFletesBundle\Admin\AgenciaAdmin
        tags:
            - {name: sonata.admin, manager_type: orm, group: Operacionales, label: "Agencias"}
        arguments:
              - ~
              - Timsa\ControlFletesBundle\Entity\Agencia
              - 'TimsaControlFletesBundle:Admin'

    sonata.admin.tarifa:
        class: Timsa\ControlFletesBundle\Admin\TarifaAdmin
        tags:
            - {name: sonata.admin, manager_type: orm, group: Operacionales, label: "Tarifas"}
        arguments:
              - ~
              - Timsa\ControlFletesBundle\Entity\Tarifa
              - 'TimsaControlFletesBundle:Admin'

    sonata.admin.tarifa_agencia:
        class: Timsa\ControlFletesBundle\Admin\TarifaAgenciaAdmin
        tags:
            - {name: sonata.admin, manager_type: orm, group: Operacionales, label: "TarifaAgencias"}
        arguments:
              - ~
              - Timsa\ControlFletesBundle\Entity\TarifaAgencia
              - 'TimsaControlFletesBundle:Admin'

    sonata.admin.cuota:
        class: Timsa\ControlFletesBundle\Admin\CuotaAdmin
        tags:
            - {name: sonata.admin, manager_type: orm, group: Operacionales, label: "Cuota"}
        arguments:
              - ~
              - Timsa\ControlFletesBundle\Entity\Cuota
              - 'TimsaControlFletesBundle:Admin'

    sonata.admin.contenedor:
        class: Timsa\ControlFletesBundle\Admin\ContenedorAdmin
        tags:
            - {name: sonata.admin, manager_type: orm, group: Administrativos, label: "Contenedores"}
        arguments:
              - ~
              - Timsa\ControlFletesBundle\Entity\Contenedor
              - 'TimsaControlFletesBundle:Admin'

    sonata.admin.sello:
        class: Timsa\ControlFletesBundle\Admin\SelloAdmin
        tags:
            - {name: sonata.admin, manager_type: orm, group: Administrativos, label: "Sellos"}
        arguments:
              - ~
              - Timsa\ControlFletesBundle\Entity\Sello
              - 'TimsaControlFletesBundle:Admin'

    sonata.admin.workorder:
        class: Timsa\ControlFletesBundle\Admin\WorkOrderAdmin
        tags:
            - {name: sonata.admin, manager_type: orm, group: Administrativos, label: "WorkOrder"}
        arguments:
              - ~
              - Timsa\ControlFletesBundle\Entity\WorkOrder
              - 'TimsaControlFletesBundle:Admin'

    sonata.admin.booking:
        class: Timsa\ControlFletesBundle\Admin\BookingAdmin
        tags:
            - {name: sonata.admin, manager_type: orm, group: Administrativos, label: "Booking"}
        arguments:
              - ~
              - Timsa\ControlFletesBundle\Entity\Booking
              - 'TimsaControlFletesBundle:Admin'

    sonata.admin.flete:
        class: Timsa\ControlFletesBundle\Admin\FleteAdmin
        tags:
            - {name: sonata.admin, manager_type: orm, group: Administrativos, label: "Fletes"}
        arguments:
              - ~
              - Timsa\ControlFletesBundle\Entity\Flete
              - 'TimsaControlFletesBundle:Admin'

    sonata.admin.user:
        class: Timsa\ControlFletesBundle\Admin\UserAdmin
        tags:
             - {name: sonata.admin, manager_type: orm, group: Usuarios, label: "Usuarios" }
        arguments:
            - ~
            - Timsa\ControlFletesBundle\Entity\User
            - 'TimsaControlFletesBundle:Admin'
        calls:
            #- [encryptPassword, ["@my_mailer"]]

    sonata.admin.groups:
        class: Timsa\ControlFletesBundle\Admin\GroupAdmin
        tags:
            - {name: sonata.admin, manager_type: orm, group: Usuarios, label: "Grupos"}
        arguments:
              - ~
              - Timsa\ControlFletesBundle\Entity\Group
              - 'TimsaControlFletesBundle:Admin'