services:
    sonata.admin.socio:
        class: Timsa\ControlFletesBundle\Admin\SocioAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: Principales, label: "Socio" }
        arguments:
            - ~
            - Timsa\ControlFletesBundle\Entity\Socio
            - 'TimsaControlFletesBundle:Admin'
        calls:
            - [ setTranslationDomain, [YourNSAdminBundle]]

    sonata.admin.user:
        class: Timsa\ControlFletesBundle\Admin\UserAdmin
        tags:
             - {name: sonata.admin, manager_type: orm, group: Usuarios, label: "Usuarios" }
        arguments:
            - ~
            - Timsa\ControlFletesBundle\Entity\User
            - 'TimsaControlFletesBundle:Admin'
        calls:
            #- [encryptPassword, ["@my_mailer"]]


    sonata.admin.operador:
        class: Timsa\ControlFletesBundle\Admin\OperadorAdmin
        tags:
              - {name: sonata.admin, manager_type: orm, group: Principales, label: "Operadores"}
        arguments:
              - ~
              - Timsa\ControlFletesBundle\Entity\Operador
              - 'TimsaControlFletesBundle:Admin'

 #   sonata.admin.role:
 #       class: Timsa\ControlFletesBundle\Admin\RoleAdmin
  #      tags:
  #          - {name: sonata.admin, manager_type: orm, group: Usuarios, label: "Roles"}
  #      arguments:
  #            - ~
   #           - Timsa\ControlFletesBundle\Entity\Role
  #            - 'TimsaControlFletesBundle:Admin'

    sonata.admin.economico:
        class: Timsa\ControlFletesBundle\Admin\EconomicoAdmin
        tags:
            - {name: sonata.admin, manager_type: orm, group: Principales, label: "Economico"}
        arguments:
              - ~
              - Timsa\ControlFletesBundle\Entity\Economico
              - 'TimsaControlFletesBundle:Admin'

    sonata.admin.relacion:
        class: Timsa\ControlFletesBundle\Admin\RelacionAdmin
        tags:
            - {name: sonata.admin, manager_type: orm, group: Principales, label: "Relacion"}
        arguments:
              - ~
              - Timsa\ControlFletesBundle\Entity\Relacion
              - 'TimsaControlFletesBundle:Admin'

    sonata.admin.cliente:
        class: Timsa\ControlFletesBundle\Admin\ClienteAdmin
        tags:
            - {name: sonata.admin, manager_type: orm, group: Operacionales, label: "Clientes"}
        arguments:
              - ~
              - Timsa\ControlFletesBundle\Entity\Cliente
              - 'TimsaControlFletesBundle:Admin'

    sonata.admin.sucursal:
        class: Timsa\ControlFletesBundle\Admin\SucursalAdmin
        tags:
            - {name: sonata.admin, manager_type: orm, group: Operacionales, label: "Sucursales"}
        arguments:
              - ~
              - Timsa\ControlFletesBundle\Entity\Sucursal
              - 'TimsaControlFletesBundle:Admin'

    sonata.admin.agencia:
        class: Timsa\ControlFletesBundle\Admin\AgenciaAdmin
        tags:
            - {name: sonata.admin, manager_type: orm, group: Operacionales, label: "Agencias"}
        arguments:
              - ~
              - Timsa\ControlFletesBundle\Entity\Agencia
              - 'TimsaControlFletesBundle:Admin'

    sonata.admin.tarifa:
        class: Timsa\ControlFletesBundle\Admin\TarifaAdmin
        tags:
            - {name: sonata.admin, manager_type: orm, group: Operacionales, label: "Tarifas"}
        arguments:
              - ~
              - Timsa\ControlFletesBundle\Entity\Tarifa
              - 'TimsaControlFletesBundle:Admin'

    sonata.admin.tarifa_agencia:
        class: Timsa\ControlFletesBundle\Admin\TarifaAgenciaAdmin
        tags:
            - {name: sonata.admin, manager_type: orm, group: Operacionales, label: "TarifaAgencias"}
        arguments:
              - ~
              - Timsa\ControlFletesBundle\Entity\TarifaAgencia
              - 'TimsaControlFletesBundle:Admin'

    sonata.admin.cuota:
        class: Timsa\ControlFletesBundle\Admin\CuotaAdmin
        tags:
            - {name: sonata.admin, manager_type: orm, group: Operacionales, label: "Cuota"}
        arguments:
              - ~
              - Timsa\ControlFletesBundle\Entity\Cuota
              - 'TimsaControlFletesBundle:Admin'

    sonata.admin.groups:
        class: Timsa\ControlFletesBundle\Admin\GroupAdmin
        tags:
            - {name: sonata.admin, manager_type: orm, group: Usuarios, label: "Grupos"}
        arguments:
              - ~
              - Timsa\ControlFletesBundle\Entity\Group
              - 'TimsaControlFletesBundle:Admin'