login:
    pattern:  /login
    defaults: {_controller: TimsaControlFletesBundle:Security:login}

login_check:
    pattern:  /main/login_check

_homepage:
    pattern:  /
    defaults: { _controller: TimsaControlFletesBundle:Principal:index }

_operadores:
    pattern: /main/operador
    defaults: { _controller: TimsaControlFletesBundle:Operador:index }

_crearOperador:
    pattern: /main/operador/crear
    defaults: {_controller: TimsaControlFletesBundle:Operador:create}

_socios:
    pattern: /main/socio
    defaults: { _controller: TimsaControlFletesBundle:Socio:index }

_economicos:
    pattern: /main/economico
    defaults: {_controller: TimsaControlFletesBundle:Economico:index }

_clientes:
    pattern: /main/cliente
    defaults: {_controller: TimsaControlFletesBundle:Cliente:index }

_cuotas:
    pattern: /main/cuota
    defaults: {_controller: TimsaControlFletesBundle:Cuota:index }

_fletes:
    pattern: /main/flete
    defaults: {_controller: TimsaControlFletesBundle:Flete:index }

_procesar:
    pattern: /main/procesar/{tipo}
    defaults: {_controller: TimsaControlFletesBundle:Procesar:index}