#login:
    #pattern:  /login

#login_check:
#    pattern:  /main/login_check

#logout:
    #pattern: /logout

_entrada:
    pattern: /
    defaults: 
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: /main
        permanent: true

_homepage:
    pattern:  /main
    defaults: { _controller: TimsaControlFletesBundle:Principal:index }

_operadores:
    pattern: /main/operador/
    defaults: { _controller: TimsaControlFletesBundle:Operador:index, busqueda: ""}
    #requirements:
        #ocupado: \d+
        #libre: \d+

#_crearOperador:
    #pattern: /main/operador/crear
    #defaults: {_controller: TimsaControlFletesBundle:Operador:create}

_economicos:
    pattern: /main/economico
    defaults: {_controller: TimsaControlFletesBundle:Economico:index }

_socio:
    pattern: /main/socio/{idSocio}
    defaults: { _controller: TimsaControlFletesBundle:Economico:ajaxSocio }

_clientes:
    pattern: /main/cliente
    defaults: {_controller: TimsaControlFletesBundle:Cliente:index }

_cuotas:
    pattern: /main/cuota
    defaults: {_controller: TimsaControlFletesBundle:Cuota:index }

_fletes:
    pattern: /main/flete
    defaults: {_controller: TimsaControlFletesBundle:Flete:index }

_tarifa:
    pattern: /main/tarifa/{idAgencia}
    defaults: {_controller: TimsaControlFletesBundle:Tarifa:index}

#_procesar:
    #pattern: /main/procesar/{tipo}
    #defaults: {_controller: TimsaControlFletesBundle:Procesar:index}