#login:
    #pattern:  /login

#login_check:
#    pattern:  /main/login_check

#logout:
    #pattern: /logout

_entrada:
    pattern: /
    defaults: 
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: /main
        permanent: true

_homepage:
    pattern:  /main
    defaults: { _controller: TimsaControlFletesBundle:Principal:index }

_operadores:
    pattern: /main/operador/
    defaults: { _controller: TimsaControlFletesBundle:Operador:index, busqueda: ""}
    #requirements:
        #ocupado: \d+
        #libre: \d+

#_crearOperador:
    #pattern: /main/operador/crear
    #defaults: {_controller: TimsaControlFletesBundle:Operador:create}

_economicos:
    pattern: /main/economico
    defaults: {_controller: TimsaControlFletesBundle:Economico:index }

_socio:
    pattern: /main/socio/{idSocio}
    defaults: { _controller: TimsaControlFletesBundle:Economico:ajaxSocio }

_clientes:
    pattern: /main/cliente
    defaults: {_controller: TimsaControlFletesBundle:Cliente:index }

_cuotas:
    pattern: /main/cuota
    defaults: {_controller: TimsaControlFletesBundle:Cuota:index }
#Antes el controlador era index
_fletes:
    pattern: /main/flete
    defaults: {_controller: TimsaControlFletesBundle:Flete:list }

_tarifa:
    pattern: /main/tarifa/{idAgencia}
    defaults: {_controller: TimsaControlFletesBundle:Tarifa:index}
    requirements:
        idAgencia: \d+

#_procesar:
    #pattern: /main/procesar/{tipo}
    #defaults: {_controller: TimsaControlFletesBundle:Procesar:index}

_contenedores:
    pattern: /main/contenedores
    defaults: {_controller: TimsaControlFletesBundle:Contenedor:index}

flete_detalle:
    pattern: /main/fleteDetalle/{flete}
    defaults: {_controller: TimsaControlFletesBundle:Flete:detalle, flete: 0 }
    requirements:
        flete: \d+

create_flete:
   pattern: /main/CreateFlete
   defaults: {_controller: TimsaControlFletesBundle:Flete:create}

create_new_flete:
  pattern: /main/flete/create
  defaults: {_controller: TimsaControlFletesBundle:Flete:createFlete}

_filtro:
   pattern: /main/filtro
   defaults: {_controller: TimsaControlFletesBundle:Flete:ajax}

_sucursales:
   pattern: /main/sucursal/{idCliente}
   defaults: {_controller: TimsaControlFletesBundle:Cliente:sucursal}
   requirements:
       idCliente: \d+

_createSucursal:
   pattern: /main/sucursal/create
   defaults: {_controller: TimsaControlFletesBundle:Cliente:create}

_tarifaDetalle:
   pattern: /main/tarifa/detalle
   defaults: {_controller: TimsaControlFletesBundle:Tarifa:ajax}

_posicionSucursales:
   pattern: /main/sucursal/posicion/{cliente}
   defaults: {_controller: TimsaControlFletesBundle:Cliente:posicion, cliente:0}

#flete_create:
 #  pattern: /main/flete/list
#   defaults: {_controller: TimsaControlFletesBundle:Flete:list}

_angularPartials:
  pattern: /main/angularPartials/{file}
  defaults: {_controller: TimsaControlFletesBundle:Partial:index, format: ~}
  options:
      expose: true
  requirements:
       _method: GET

_fleteRestAll:
  pattern: /main/rest/flete
  defaults: { _controller:TimsaControlFletesBundle:FleteRest:week, format: html }
  requirements:
     _method: GET

_tarifaAgenciaRest:
   pattern: /main/rest/agencia/tarifas/{agencia}
   defaults: { _controller: TimsaControlFletesBundle:TarifaAgenciaRest:cuotaAgencia, format: ~ }
   requirements:
      _method: GET

_tarifaRest:
   pattern: /main/rest/tarifa
   defaults: { _controller: TimsaControlFletesBundle:TarifaAgenciaRest:tarifa, format: ~ }
   requirements:
      _method: GET

_tarifaCuotaRest:
   pattern: /main/rest/cuota
   defaults: { _controller: TimsaControlFletesBundle:TarifaAgenciaRest:cuota, format: ~ }
   requirements:
      _method: GET

