parameters:
#    timsa_control_fletes.example.class: Timsa\ControlFletesBundle\Example

services:
#    timsa_control_fletes.example:
#        class: %timsa_control_fletes.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]

    pass_encoder:
        class: Timsa\ControlFletesBundle\Entity\UserEncoder
