Timsa\ControlFletesBundle\Entity\Operador:
    properties:
        nombre:
           - NotBlank: ~
        telefono:
           - Length:
               min: 7
               max: 12
               minMessage: El numero de telefono es demasiado pequeño.
               maxMessage: El numero de telefono tiene demasiados caracteres.
           - Regex:
               pattern: "/\d+/"
               message: Your name cannot contain a number

Timsa\ControlFletesBundle\Entity\Flete:
    properties:
        relacion:
           - NotBlank: ~
        agencia:
           - NotBlank: ~
        sucursal:
           - NotBlank: ~