<?php

namespace Proxies\__CG__\Timsa\ControlFletesBundle\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Economico extends \Timsa\ControlFletesBundle\Entity\Economico implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function setPlacas($placas)
    {
        $this->__load();
        return parent::setPlacas($placas);
    }

    public function getPlacas()
    {
        $this->__load();
        return parent::getPlacas();
    }

    public function setStatusA($statusA)
    {
        $this->__load();
        return parent::setStatusA($statusA);
    }

    public function getStatusA()
    {
        $this->__load();
        return parent::getStatusA();
    }

    public function setFechaIngreso($fechaIngreso)
    {
        $this->__load();
        return parent::setFechaIngreso($fechaIngreso);
    }

    public function getFechaIngreso()
    {
        $this->__load();
        return parent::getFechaIngreso();
    }

    public function setFechaSalida($fechaSalida)
    {
        $this->__load();
        return parent::setFechaSalida($fechaSalida);
    }

    public function getFechaSalida()
    {
        $this->__load();
        return parent::getFechaSalida();
    }

    public function setNumeroSerie($numeroSerie)
    {
        $this->__load();
        return parent::setNumeroSerie($numeroSerie);
    }

    public function getNumeroSerie()
    {
        $this->__load();
        return parent::getNumeroSerie();
    }

    public function setModelo($modelo)
    {
        $this->__load();
        return parent::setModelo($modelo);
    }

    public function getModelo()
    {
        $this->__load();
        return parent::getModelo();
    }

    public function setTransponder($transponder)
    {
        $this->__load();
        return parent::setTransponder($transponder);
    }

    public function getTransponder()
    {
        $this->__load();
        return parent::getTransponder();
    }

    public function setMarca($marca)
    {
        $this->__load();
        return parent::setMarca($marca);
    }

    public function getMarca()
    {
        $this->__load();
        return parent::getMarca();
    }

    public function setTipoVehiculo($tipoVehiculo)
    {
        $this->__load();
        return parent::setTipoVehiculo($tipoVehiculo);
    }

    public function getTipoVehiculo()
    {
        $this->__load();
        return parent::getTipoVehiculo();
    }

    public function __toString()
    {
        $this->__load();
        return parent::__toString();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'placas', 'statusA', 'fechaIngreso', 'fechaSalida', 'numeroSerie', 'modelo', 'transponder', 'marca', 'tipoVehiculo', 'relacion');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}