# Archivo de seguridad de Symfony.
security:
    #Codificadores.
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512
        #Timsa\ControlFletesBundle\Entity\User: #Entidad
           #id:  pass_encoder
          # algorithm: sha1
          # encode_as_base64: false
         #  iterations: 1    #NUmero de veces que se aplica el algoritmo. Default 5000

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

#    providers: #Provedores de usuarios.
#        administradores:
#             entity: {class: TimsaControlFletesBundle:User, property: username}

    providers:
           fos_userbundle:
               id: fos_user.user_provider.username


    firewalls:
        aplicacion:                     #Nombre del firewall
            pattern:    ^/main          #Expresion regular. Que URL protege el firewall.
            #provider:   administradores #Especifica que proveedor utiliza este firewall.
            form_login:                 #Especifica la forma en que se autentifica el usuario. Alternativa a http_basic
                provider:      fos_userbundle
                csrf_provider: form.csrf_provider
                #login_path: login
                #check_path: login_check
            logout:       true
            anonymous:    true
                #path: logout
            #http_basic: ~
            #anonymous: ~
            #http_basic:
            #    realm: "Secured Demo Area"
            acl:
                connection: default

    access_control:                     #Especifica los permisos que se necesitan para acceder a determinadas rutas.
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/main,   roles: ROLE_USER   }
        - { path: ^/admin,  roles: ROLE_ADMIN }
