<?php

namespace Timsa\ControlFletesBundle\Entity\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EconomicoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EconomicoRepository extends EntityRepository
{
}
