<?php

namespace Timsa\ControlFletesBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EconomicoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FleteRepository extends EntityRepository
{

	public function getFiltroFlete($flete){
		return $this->getEntityManager()
					->createQuery("SELECT f.fecha, f.actividad, f.comentarios, f.fecha_llegada,
										  f.fecha_facturacion, op.nombre 
								   FROM TimsaControlFletesBundle:Flete f
									JOIN f.relacion   r
									JOIN r.operador   op
									JOIN r.economico  ec
									JOIN r.socio 	  so
									JOIN f.agencia    ag
									JOIN f.fletePadre fp
									JOIN f.fleteHijo  fh
									JOIN f.sucursal   su
									JOIN f.cuota  	  cu
									JOIN f.tipo_viaje tv

									WHERE p.id = $flete ")
					->getResult();
	}
}
