<?php

namespace Timsa\ControlFletesBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EconomicoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FleteRepository extends EntityRepository
{

	public function getFiltroFlete($flete){
		return $this->getEntityManager()
					->createQuery("SELECT f.fecha, f.actividad, f.comentarios, f.fecha_llegada,
										  f.fecha_facturacion, op.nombre 
								   FROM TimsaControlFletesBundle:Flete f
									JOIN f.relacion   r
									JOIN r.operador   op
									JOIN r.economico  ec
									JOIN r.socio 	  so
									JOIN f.agencia    ag
									JOIN f.fletePadre fp
									JOIN f.fleteHijo  fh
									JOIN f.sucursal   su
									JOIN f.cuota  	  cu
									JOIN f.tipo_viaje tv

									WHERE p.id = $flete ")
					->getResult();
	}

	public function findAllFletes(){
		return $this->getEntityManager()
					->createQuery("SELECT f.id,
										  f.fecha,
										  ac.actividad,
										  f.comentarios,
										  f.fecha_llegada,
										  f.fecha_facturacion,
										  op.id as OperadorID,
										  op.nombre as Operador,
										  ec.id as EconomicoID,
										  ec.numero as Economico,
										  so.id as SocioID,
										  so.nombre as SocioNombre,
										  cl.id as SucursalID,
										  cl.nombre as Cliente,
										  CONCAT( CONCAT(tv.viaje ,' '), tv.trafico ) as Trafico


								   FROM TimsaControlFletesBundle:Flete f

								   LEFT JOIN f.actividad ac
								   LEFT JOIN f.relacion   r
								   LEFT JOIN r.operador   op
								   LEFT JOIN r.economico  ec
								   LEFT JOIN r.socio 	 so
								   LEFT JOIN f.sucursal   su
								   LEFT JOIN su.cliente   cl
								   LEFT JOIN f.tipo_viaje tv

								   order by f.id"
								   )
					->getResult();
	}

	public function fleteWorkorders( $flete ){
		return $this->getEntityManager()
					->createQuery("SELECT 
										wo.workorder as Workorder,
										c.codigo as Contenedor,
										c.tipo as Type,
										bo.booking as Booking

									FROM TimsaControlFletesBundle:WorkOrder wo
									INNER JOIN wo.contenedor c
									INNER JOIN wo.booking bo

									WHERE w.flete = $flete
								  ");
	}
}

/*


fh.id as FleteHijo,


JOIN f.fleteHijo  fh

*/