<?php

namespace Timsa\ControlFletesBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * OperadorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OperadorRepository extends EntityRepository
{
	public function getOperadoresLibres(){
		return $this->getEntityManager()
					->createQuery("SELECT p FROM TimsaControlFletesBundle:Operador p 
											WHERE p.actividad = 1 
											ORDER BY p.nombre")
					->getResult();
	}

	public function getOperadoresOcupados(){
		return $this->getEntityManager()
					->createQuery("SELECT p FROM TimsaControlFletesBundle:Operador p 
											WHERE p.actividad = 2 
											ORDER BY p.nombre")
					->getResult();
	}

	public function getLikeOperadoresLibres($nombre){
		return $this->getEntityManager()
					->createQuery("SELECT p FROM TimsaControlFletesBundle:Operador p 
											WHERE p.actividad = 1
											and
											p.nombre LIKE '%$nombre%' 
											ORDER BY p.nombre")
					->getResult();
	}

	public function getLikeOperadoresOcupados($nombre){
		return $this->getEntityManager()
					->createQuery("SELECT p FROM TimsaControlFletesBundle:Operador p 
											WHERE p.actividad = 2
											and
											p.nombre LIKE '%$nombre%' 
											ORDER BY p.nombre")
					->getResult();
	}

    public function getAll(){
        return $this->getEntityManager()
            ->createQuery("SELECT op.id, op.nombre, a.id
                            FROM TimsaControlFletesBundle:Operador op
                                 JOIN op.actividad a
                            WHERE op.statusA = true
                            ORDER BY op.nombre")
            ->getResult();
    }
}
