<?php

namespace Timsa\ControlFletesBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EconomicoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RelacionRepository extends EntityRepository
{
	public function filtrarRelaciones($numero){
		$query = "SELECT r FROM TimsaControlFletesBundle:Relacion r
											JOIN r.economico e
											WHERE e.numero LIKE  '%$numero%'";

		return $this->getEntityManager()
					->createQuery( $query )
					->getResult();
	}

	public function getRelacion($numero){
		$query = "SELECT e.numero economico, a.actividad statusEconomico , o.nombre nombreOperador, ac.actividad statusOperador, s.nombre nombreSocio
					FROM TimsaControlFletesBundle:Relacion r
											JOIN r.economico e
											JOIN r.operador  o
											JOIN r.socio     s
											JOIN e.actividad a
											JOIN o.actividad ac
											WHERE r.id LIKE  '%$numero%' 
											and r.statusA = true";

		return $this->getEntityManager()
					->createQuery( $query )
					->getResult();
	}

    public function findRelaciones(){
        return $this->getEntityManager()
            ->createQuery(" SELECT op.id as operadorID, op.nombre as operador,ao.id as actividad_operador,
                                   e.id as economicoID, e.numero as economico, ae.id as actividad_economico,
                                   s.id as socioID, s.nombre as socio,
                                   r.id as ID
                            FROM TimsaControlFletesBundle:Relacion r
                            JOIN r.operador op
                            JOIN op.actividad ao
                            JOIN r.economico e
                            JOIN e.actividad ae
                            JOIN r.socio s
                            WHERE r.statusA = true
                            ")
            ->getResult();
    }
}
