<?php

namespace Timsa\ControlFletesBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SocioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SocioRepository extends EntityRepository
{

	public function findAllActive(){
		return $this->getEntityManager()
					->createQuery("SELECT p FROM TimsaControlFletesBundle:Socio p 
											WHERE p.statusA = true ")
					->getResult();
	}
}
