<?php

namespace Timsa\ControlFletesBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * OperadorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SucursalRepository extends EntityRepository
{
	public function getSucursalesPorCliente($cliente){
		return $this->getEntityManager()
					->createQuery("SELECT p FROM TimsaControlFletesBundle:Sucursal p 
											WHERE p.cliente =  $cliente
											ORDER BY p.nombre")
					->getResult();
	}

}
