<?php

namespace Timsa\ControlFletesBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SocioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TarifaAgenciaRepository extends EntityRepository
{
		public function findTarifaPorAgencia($agencia){

			return $this->getEntityManager()
						->createQuery("SELECT t.nombre as tarifa, s.nombre as destino, c.exportacionSencillo as exportacions,
										c.importacionSencillo as importacions, c.reutilizadoSencillo as reutilizados,
										c.exportacionFull as exportacionf, c.importacionFull as importacionf,
										c.reutilizadoFull as reutilizadof
									   FROM

									   TimsaControlFletesBundle:TarifaAgencia ta

									   JOIN ta.cuota  c
									   JOIN ta.tarifa t
									   JOIN t.sucursales s
									   where 
									   ta.statusA = true and
									   ta.agencia = $agencia"
									   )
						->getResult();
		}
/*
		public function findTarifaPorAgencia($agencia){

			return $this->getEntityManager()
						->createQuery("SELECT t.nombre, c.nombre
									   FROM 

									   TimsaControlFletesBundle:TarifaAgencia ta

									   JOIN TimsaControlFletesBundle:Cuota c 
									   JOIN TimsaControlFletesBundle:Tarifa t
									   where 
									   ta.cuota = c.id
									   and 
									   ta.tarifa = t.id
									   and 
									   ta.agencia = $agencia

									   ORDER BY r.prioridad")
						->getResult();
		}

		#, c.importacionSencillo as is, c.reutilizadoSencillo as rs, c.exportacionFull as ef, c.importacionFull as if, c.reutilizadoFull as rf
	*/
}
