<?php

namespace Timsa\ControlFletesBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SocioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TarifaAgenciaRepository extends EntityRepository
{
		public function findTarifaPorAgencia($agencia){

			return $this->getEntityManager()
						->createQuery("SELECT t.nombre as tarifa, t.id idTarifa , c.exportacionSencillo as exportacions,
										c.importacionSencillo as importacions, c.reutilizadoSencillo as reutilizados,
										c.exportacionFull as exportacionf, c.importacionFull as importacionf,
										c.reutilizadoFull as reutilizadof
									   FROM

									   TimsaControlFletesBundle:TarifaAgencia ta

									   JOIN ta.cuota  c
									   JOIN ta.tarifa t
									   where 
									   ta.statusA = true and
									   ta.agencia = $agencia"
									   )
						->getResult();
		}

		public function findCuotaActiva($tarifa, $agencia){
			$entidadTarifa =  $tarifa->last()->getId();
			$entidadAgencia = $agencia->getId();

			return $this->getEntityManager()
						->createQuery("SELECT ta
									   FROM 
									   TimsaControlFletesBundle:TarifaAgencia ta
									   WHERE
									   ta.tarifa = $entidadTarifa and
									   ta.agencia = $entidadAgencia")
						->setMaxResults(1)
						->getResult();
		}

/*
		public function findDetalleTarifaActual($agencia, $tarifa){

			return $this->getEntityManager()
						->createQuery("SELECT t.nombre as tarifa, t.id idTarifa , s.nombre as destino, c.exportacionSencillo as exportacions,
										c.importacionSencillo as importacions, c.reutilizadoSencillo as reutilizados,
										c.exportacionFull as exportacionf, c.importacionFull as importacionf,
										c.reutilizadoFull as reutilizadof
									   FROM

									   TimsaControlFletesBundle:TarifaAgencia ta

									   JOIN ta.cuota  c
									   JOIN ta.tarifa t
									   JOIN t.sucursales s
									   where
									   ta.statusA = true and
									   ta.agencia = $agencia and
									   ta.tarifa  = $tarifa"
									   )
						->getResult();
		}
*/

		public function findDetalleTarifas($agencia, $tarifa){

			return $this->getEntityManager()
						->createQuery("SELECT ta.clasificacion titulo, ta.statusA status, t.nombre as tarifa, t.id idTarifa , c.exportacionSencillo as exportacions,
										c.importacionSencillo as importacions, c.reutilizadoSencillo as reutilizados,
										c.exportacionFull as exportacionf, c.importacionFull as importacionf,
										c.reutilizadoFull as reutilizadof
									   FROM

									   TimsaControlFletesBundle:TarifaAgencia ta

									   JOIN ta.cuota  c
									   JOIN ta.tarifa t
									   where
									   ta.agencia = $agencia and
									   ta.tarifa  = $tarifa
									   order by ta.fecha_ingreso"									   
									   )
						->getResult();
		}

        public function findTarifaByAgencia($agencia){
            return $this->getEntityManager()
                        ->createQuery("SELECT t.nombre as tarifa, t.id idTarifa , c.exportacionSencillo as exportacions,
										c.importacionSencillo as importacions, c.reutilizadoSencillo as reutilizados,
										c.exportacionFull as exportacionf, c.importacionFull as importacionf,
										c.reutilizadoFull as reutilizadof,
										ta.clasificacion, c.nombre as nombre_cuota,
										ta.fecha_ingreso as fecha, ta.id as cuota, ta.id as id
									   FROM

									   TimsaControlFletesBundle:TarifaAgencia ta

									   JOIN ta.cuota  c
									   JOIN ta.tarifa t
									   where
									   ta.statusA = true and
									   ta.agencia = $agencia"
                                     )
                        ->getResult();
        }

    public function deshabilitarTarifa($clase, $tarifa, $agencia){
        return $this->getEntityManager()
            ->createQuery(" UPDATE
                            TimsaControlFletesBundle:TarifaAgencia ta SET ta.statusA = false
                            WHERE
                            ta.statusA = true
                            AND
                            ta.tarifa = $tarifa
                            AND
                            ta.agencia = $agencia
                            AND
                            ta.clasificacion =  $clase
                            ")
            ->getResult();
    }

    public function eliminarTarifaPorAgencia($clase, $tarifa, $agencia, $cuota){
        return $this->getEntityManager()
            ->createQuery(" UPDATE
                            TimsaControlFletesBundle:TarifaAgencia ta SET ta.statusA = false
                            WHERE
                            ta.statusA = true
                            AND
                            ta.tarifa = $tarifa
                            AND
                            ta.agencia = $agencia
                            AND
                            ta.clasificacion =  $clase
                            AND
                            ta.cuota = $cuota
                            ")
            ->getResult();
    }

    public function removeTarifaPorAgencia($id){
        return $this->getEntityManager()
            ->createQuery(" UPDATE
                            TimsaControlFletesBundle:TarifaAgencia ta SET ta.statusA = false
                            WHERE
                            ta.statusA = true
                            AND
                            ta.id = $id
                            ")
            ->getResult();
    }
/*
		public function findTarifaPorAgencia($agencia){

			return $this->getEntityManager()
						->createQuery("SELECT t.nombre, c.nombre
									   FROM 

									   TimsaControlFletesBundle:TarifaAgencia ta

									   JOIN TimsaControlFletesBundle:Cuota c 
									   JOIN TimsaControlFletesBundle:Tarifa t
									   where 
									   ta.cuota = c.id
									   and 
									   ta.tarifa = t.id
									   and 
									   ta.agencia = $agencia

									   ORDER BY r.prioridad")
						->getResult();
		}

		#, c.importacionSencillo as is, c.reutilizadoSencillo as rs, c.exportacionFull as ef, c.importacionFull as if, c.reutilizadoFull as rf
	*/
}
